spring.application.name=recipemanager

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/recipe}

logging.level.org.springframework.data.mongodb.core=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}