spring.application.name=recipemanager

spring.data.mongodb.connection-string=${SPRING_DATA_MONGODB_URI:${SPRING_MONGODB_URI:mongodb://localhost:27017/recipemanager}}


logging.level.org.springframework.data.mongodb.core=DEBUG

# will change it later to more secure place
jwt.secret=${JWT_SECRET:your-32-char-minimum-secret-key!!}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}